# Generated by Django 5.2 on 2026-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="api_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
