# Generated by Django 5.2 on 2026-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_match_api_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("n_simulations", models.IntegerField()),
                ("data", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
    ]
