# Generated by Django 5.2 on 2026-05-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_simulationsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="stage",
            field=models.CharField(
                choices=[
                    ("LEAGUE", "Liga"),
                    ("GROUP", "Faza grupowa"),
                    ("R32", "1/16 finału"),
                    ("R16", "1/8 finału"),
                    ("QF", "Ćwierćfinał"),
                    ("SF", "Półfinał"),
                    ("3RD", "Mecz o 3. miejsce"),
                    ("FINAL", "Finał"),
                ],
                max_length=10,
            ),
        ),
    ]
