# Generated by Django 5.2 on 2026-05-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_league_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_score_90",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score_90",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
