# Generated by Django 5.2 on 2026-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_score_90"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_score_80",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score_80",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
